# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "ARGUMENT", :id => false, :force => true do |t|
    t.column "CODE",   :string,  :limit => 32,                               :null => false
    t.column "SN",     :integer,               :precision => 8, :scale => 0, :null => false
    t.column "NAME",   :string,  :limit => 32
    t.column "VALUE",  :string,  :limit => 32
    t.column "VALUE2", :string,  :limit => 32
    t.column "REMARK", :string
  end

  create_table "CCWORD_PY", :id => false, :force => true do |t|
    t.column "PY", :string, :limit => 1, :null => false
    t.column "HZ", :string, :limit => 2, :null => false
  end

  create_table "CHG_DATABASE_RECORD", :id => false, :force => true do |t|
    t.column "ID",             :integer,                 :precision => 10, :scale => 0, :null => false
    t.column "CHG_NO",         :string,   :limit => 20,                                 :null => false
    t.column "MODIFY_DATE",    :datetime
    t.column "TABLE_NAME",     :string,   :limit => 32
    t.column "COLUMN_NAME",    :string,   :limit => 32
    t.column "PROBLEM_DETAIL", :string,   :limit => 200
    t.column "MODIFY_DETAIL",  :string,   :limit => 200
    t.column "MODIFY_PERSON",  :string,   :limit => 32
  end

  add_index "CHG_DATABASE_RECORD", ["ID"], :name => "AK_AK_DATEBASE_MODIFY_CHG_DATA", :unique => true

  create_table "CHG_DOCUMENT_RECORD", :id => false, :force => true do |t|
    t.column "ID",               :integer,                 :precision => 10, :scale => 0, :null => false
    t.column "CHG_NO",           :string,   :limit => 20,                                 :null => false
    t.column "MODIFY_TIME",      :datetime
    t.column "SUB_SYSTEM",       :string,   :limit => 20
    t.column "OBJECT_NAME",      :string,   :limit => 20
    t.column "PROBLEM_DESCRIBE", :string,   :limit => 200
    t.column "MODIFY_NOTE",      :string,   :limit => 200
    t.column "MODIRY_PERSON",    :string,   :limit => 32
    t.column "PROBLEM_KIND",     :string,   :limit => 10
    t.column "COMMENT",          :string,   :limit => 10
  end

  add_index "CHG_DOCUMENT_RECORD", ["ID"], :name => "AK_AK_DOCUMENT_MODIFY_CHG_DOCU", :unique => true

  create_table "CHG_SOURCE_RECORD", :id => false, :force => true do |t|
    t.column "ID",               :integer,                 :precision => 10, :scale => 0, :null => false
    t.column "CHG_NO",           :string,   :limit => 20,                                 :null => false
    t.column "MODIFY_TIME",      :datetime
    t.column "SUB_SYSTEM",       :string,   :limit => 32
    t.column "APP_NAME",         :string,   :limit => 32
    t.column "OBJECT_NAME",      :string,   :limit => 32
    t.column "PROBLEM_DESCRIBE", :string,   :limit => 200
    t.column "MODIFY_NOTE",      :string,   :limit => 200
    t.column "MODIRY_PERSON",    :string,   :limit => 32
    t.column "PROBLEM_KIND",     :string,   :limit => 32
    t.column "COMMENT",          :string,   :limit => 200
  end

  add_index "CHG_SOURCE_RECORD", ["ID"], :name => "AK_AK_SOURCE_MODIFY_CHG_SOUR", :unique => true

  create_table "CONFIGURE_CHECK_REPORT", :id => false, :force => true do |t|
    t.column "ID",              :integer,                :precision => 10, :scale => 0, :null => false
    t.column "DOCUMENT_SN",     :string,   :limit => 20
    t.column "PROJECT_CODE",    :string,   :limit => 20
    t.column "RECORD_DATE",     :datetime
    t.column "CHECK_ITEM_01",   :string,   :limit => 32
    t.column "CHECK_ITEM_02",   :string,   :limit => 32
    t.column "CHECK_ITEM_03",   :string,   :limit => 32
    t.column "CHECK_ITEM_04",   :string,   :limit => 32
    t.column "CHECK_ITEM_05",   :string,   :limit => 32
    t.column "CHECK_ITEM_06",   :string,   :limit => 32
    t.column "CHECK_ITEM_07",   :string,   :limit => 32
    t.column "CHECK_ITEM_08",   :string,   :limit => 32
    t.column "CHECK_ITEM_09",   :string,   :limit => 32
    t.column "CHECK_ITEM_10",   :string,   :limit => 32
    t.column "CHECK_RESULT_01", :string,   :limit => 32
    t.column "CHECK_RESULT_02", :string,   :limit => 32
    t.column "CHECK_PERSON",    :string,   :limit => 64
    t.column "CHECK_DATE",      :datetime
  end

  add_index "CONFIGURE_CHECK_REPORT", ["DOCUMENT_SN"], :name => "AK_AK_CONFIGUR", :unique => true

  create_table "CONFIGURE_CHG_APP", :id => false, :force => true do |t|
    t.column "ID",               :integer,                :precision => 10, :scale => 0, :null => false
    t.column "CONFIGURE_CHG_NO", :string,  :limit => 20
    t.column "CONFIGURE_CODE",   :string,  :limit => 16,                                 :null => false
    t.column "EVENT_CODE",       :string,  :limit => 10,                                 :null => false
    t.column "EVENT_NAME",       :string,  :limit => 64
    t.column "RELA_EVENT_NAME",  :string,  :limit => 254
    t.column "PRE_VERSION",      :string,  :limit => 10
    t.column "AFT_VERSION",      :string,  :limit => 10
    t.column "CONFIG_CHG_TYPE",  :string,  :limit => 32
    t.column "CONF_CHG_ORDER",   :string,  :limit => 32
    t.column "PROJECT_CODE",     :string,  :limit => 20
    t.column "CURRENT_STATUS",   :string,  :limit => 10
  end

  add_index "CONFIGURE_CHG_APP", ["CONFIGURE_CHG_NO"], :name => "AK_AK_CHG_CONFIGUR", :unique => true

  create_table "CONFIGURE_CHG_CYCLE_DET", :id => false, :force => true do |t|
    t.column "ID",               :integer,                 :precision => 10, :scale => 0, :null => false
    t.column "CONFIGURE_CHG_NO", :string,   :limit => 20
    t.column "CHG_STATE",        :string,   :limit => 32
    t.column "CHG_PRSN01",       :string,   :limit => 32
    t.column "CHG_PRSN02",       :string,   :limit => 32
    t.column "CHG_DATE01",       :datetime
    t.column "CHG_DATE02",       :datetime
    t.column "WORK_DAYS",        :string,   :limit => 32
    t.column "REMARK",           :string,   :limit => 254
    t.column "ACTIVE_STATUS",    :string,   :limit => 2
  end

  create_table "CONFIGURE_COMP_LIST", :id => false, :force => true do |t|
    t.column "ID",             :integer,               :precision => 10, :scale => 0, :null => false
    t.column "CONFIGURE_CODE", :string,  :limit => 16,                                :null => false
    t.column "COMP_CODE",      :string,  :limit => 20
    t.column "COMP_NAME",      :string,  :limit => 64
    t.column "COMP_COMMENT",   :string,  :limit => 64
  end

  add_index "CONFIGURE_COMP_LIST", ["CONFIGURE_CODE", "COMP_CODE"], :name => "AK_AK_CONF_COMP_CONFIGUR", :unique => true

  create_table "CONFIGURE_ITEM", :id => false, :force => true do |t|
    t.column "ID",                   :integer,                  :precision => 10, :scale => 0, :null => false
    t.column "CONFIGURE_SN",         :string,   :limit => 10
    t.column "CONFIGURE_CODE",       :string,   :limit => 16,                                  :null => false
    t.column "CONFIGURE_NAME",       :string,   :limit => 64
    t.column "CONFIGURE_TYPE",       :string,   :limit => 32
    t.column "CONFIGURE_REMARK",     :string,   :limit => 254
    t.column "CONFIGURE_STORE_ADDR", :string,   :limit => 1022
    t.column "CONFIGURE_PUB_DATE",   :datetime
    t.column "CONF_DUTY_PERSON",     :string,   :limit => 32
    t.column "CONFIGURE_PUB_PERSON", :string,   :limit => 32
    t.column "DEVELOP_PATH",         :string,   :limit => 1024
  end

  add_index "CONFIGURE_ITEM", ["CONFIGURE_CODE"], :name => "AK_AK_CONFIG_ITEM_CONFIGUR", :unique => true

  create_table "CONFIGURE_MSG_CYCLE_DET", :id => false, :force => true do |t|
    t.column "ID",            :integer,                 :precision => 10, :scale => 0, :null => false
    t.column "EVENT_CODE",    :string,   :limit => 10,                                 :null => false
    t.column "EVENT_STATE",   :string,   :limit => 32,                                 :null => false
    t.column "EVENT_PRSN01",  :string,   :limit => 32
    t.column "EVENT_PRSN02",  :string,   :limit => 32
    t.column "REMARK_01",     :string,   :limit => 254
    t.column "REMARK_02",     :string,   :limit => 254
    t.column "REMARK_03",     :string,   :limit => 254
    t.column "CONCLUSION_01", :string,   :limit => 32
    t.column "CONCLUSION_02", :string,   :limit => 32
    t.column "WORK_DAYS01",   :string,   :limit => 32
    t.column "WORK_DAYS02",   :string,   :limit => 32
    t.column "DATE_01",       :datetime
    t.column "DATE_02",       :datetime
    t.column "ACTIVE_STATUS", :string,   :limit => 2
  end

  add_index "CONFIGURE_MSG_CYCLE_DET", ["EVENT_CODE", "EVENT_STATE"], :name => "AK_AK_EVENT_EXT_CONFIGUR", :unique => true

  create_table "CONFIGURE_VERSION", :id => false, :force => true do |t|
    t.column "ID",             :integer,                  :precision => 10, :scale => 0, :null => false
    t.column "CONFIGURE_CODE", :string,   :limit => 16,                                  :null => false
    t.column "CONFIGURE_VERS", :string,   :limit => 10
    t.column "CUR_STATE",      :string,   :limit => 32
    t.column "STATE_DATE",     :datetime
    t.column "VER_RELEASE",    :string,   :limit => 64
    t.column "RELA_ADDRESS",   :string,   :limit => 64
    t.column "COMMENT",        :string,   :limit => 30
    t.column "VERSION_FLAG",   :string,   :limit => 1
    t.column "DEVELOP_PATH",   :string,   :limit => 1024
  end

  add_index "CONFIGURE_VERSION", ["CONFIGURE_CODE", "CONFIGURE_VERS"], :name => "AK_AK_VERSION_CONFIGUR", :unique => true

  create_table "CONF_CHG_REPRODUCT_PRODUCTS", :id => false, :force => true do |t|
    t.column "ID",             :integer,               :precision => 10, :scale => 0, :null => false
    t.column "EVENT_CODE",     :string,  :limit => 10
    t.column "CONFIGURE_CODE", :string,  :limit => 16
    t.column "CONFIGURE_VERS", :string,  :limit => 10
    t.column "PRODUCT_CODE",   :string,  :limit => 10
    t.column "PRODUCT_VERS",   :string,  :limit => 15
    t.column "CAN_USE_FLAG",   :string,  :limit => 2
    t.column "EXEC_STATUS",    :string,  :limit => 8
  end

  create_table "CONF_CHG_REPROJECT_PROJECTS", :id => false, :force => true do |t|
    t.column "ID",                  :integer,               :precision => 10, :scale => 0, :null => false
    t.column "EVENT_CODE",          :string,  :limit => 10
    t.column "CONFIGURE_CODE",      :string,  :limit => 16
    t.column "CONFIGURE_VERS",      :string,  :limit => 10
    t.column "PROJECT_CODE",        :string,  :limit => 10
    t.column "CAN_USE_FLAG",        :string,  :limit => 2
    t.column "EXEC_STATUS",         :string,  :limit => 8
    t.column "NEW_IDENTIFY_STATUS", :string,  :limit => 10
    t.column "NEW_STORE_STATUS",    :string,  :limit => 10
    t.column "CHG_CIRC_STATUS",     :string,  :limit => 10
    t.column "CHG_CIRC_DETAIL",     :string,  :limit => 32
  end

  create_table "CONF_PUB_APP", :id => false, :force => true do |t|
    t.column "ID",                 :integer,                  :precision => 10, :scale => 0, :null => false
    t.column "NEW_CON_WKST_NO",    :string,   :limit => 10
    t.column "CONFIGURE_CODE",     :string,   :limit => 16
    t.column "CONFIGURE_NAME",     :string,   :limit => 64
    t.column "CONFIGURE_TYPE",     :string,   :limit => 32
    t.column "PUB_CONFIG_VER",     :string,   :limit => 10
    t.column "PUB_STORE_ADDR",     :string,   :limit => 1022
    t.column "PUB_APP_PERSON",     :string,   :limit => 32
    t.column "PUB_APP_REMARK",     :string,   :limit => 254
    t.column "PUB_APP_SIGN",       :string,   :limit => 32
    t.column "PUB_APP_DATE",       :datetime
    t.column "PUB_REMARK_01",      :string,   :limit => 254
    t.column "PUB_REMARK_02",      :string,   :limit => 254
    t.column "PUB_REMARK_03",      :string,   :limit => 254
    t.column "PUB_CONFIRM_OR_NOT", :string,   :limit => 1
    t.column "CONFIG_PERSON",      :string,   :limit => 32
    t.column "CONFIG_DET_DATE",    :datetime
    t.column "STATUS",             :string,   :limit => 2
  end

  add_index "CONF_PUB_APP", ["NEW_CON_WKST_NO", "CONFIGURE_CODE"], :name => "AK_AK_PUB_CONF_PUB", :unique => true

  create_table "CONF_PUB_APP_COMP", :id => false, :force => true do |t|
    t.column "ID",              :integer,               :precision => 10, :scale => 0, :null => false
    t.column "NEW_CON_WKST_NO", :string,  :limit => 10
    t.column "CONFIGURE_CODE",  :string,  :limit => 16
    t.column "COMP_CODE",       :string,  :limit => 20
    t.column "COMP_NAME",       :string,  :limit => 64
    t.column "COMP_COMMENT",    :string,  :limit => 64
  end

  create_table "CQ_RETRIEVE_COND", :id => false, :force => true do |t|
    t.column "COND_ID",      :integer,                :precision => 10, :scale => 0, :null => false
    t.column "SN",           :integer,                :precision => 5,  :scale => 0, :null => false
    t.column "OPERATOR",     :string,  :limit => 8,                                  :null => false
    t.column "WIN_CLASS",    :string,  :limit => 60
    t.column "DW_CLASS",     :string,  :limit => 60
    t.column "COND_NAME",    :string,  :limit => 60
    t.column "IN_USE",       :string,  :limit => 1
    t.column "WIN_TITLE",    :string,  :limit => 80
    t.column "MENU_TEXT",    :string,  :limit => 40
    t.column "MICROHELP",    :string,  :limit => 80
    t.column "TOOLBAR_TEXT", :string,  :limit => 16
    t.column "REMARK",       :string,  :limit => 128
  end

  add_index "CQ_RETRIEVE_COND", ["OPERATOR", "WIN_CLASS"], :name => "IDX_CW_RTV_COND_OPERATOR"

  create_table "CQ_RETRIEVE_COND_DEF", :id => false, :force => true do |t|
    t.column "COND_ID",       :integer,                :precision => 10, :scale => 0, :null => false
    t.column "SN",            :integer,                :precision => 5,  :scale => 0, :null => false
    t.column "LEFT_BRACKET",  :string,  :limit => 10
    t.column "COL_DISPLAY",   :string,  :limit => 60
    t.column "RELATION",      :string,  :limit => 10
    t.column "VALUE_DISPLAY", :string,  :limit => 60
    t.column "LOGIC",         :string,  :limit => 10
    t.column "RIGHT_BRACKET", :string,  :limit => 10
    t.column "WHERE_CLAUSE",  :string,  :limit => 200
    t.column "SAVE_VAL",      :string,  :limit => 1
    t.column "ITEM_DATA",     :string,  :limit => 60
    t.column "VALUE_DATA",    :string,  :limit => 60
    t.column "WHERE_ADD",     :string,  :limit => 10
    t.column "USE_DATA",      :string,  :limit => 60
  end

  create_table "CQ_SEQUENCE_COND_ID", :id => false, :force => true do |t|
    t.column "COND_ID", :integer, :precision => 10, :scale => 0, :null => false
  end

  create_table "DEPARTMENT", :id => false, :force => true do |t|
    t.column "DPT_NO",        :string,  :limit => 8,                                 :null => false
    t.column "DPT_NAME",      :string,  :limit => 64
    t.column "DPT_ADDRESS",   :string,  :limit => 64
    t.column "F_DPT_NO",      :string,  :limit => 8
    t.column "UNICODE",       :string,  :limit => 40
    t.column "DPT_TYPE",      :string,  :limit => 1
    t.column "IS_BUSI_PLACE", :string,  :limit => 1
    t.column "ID",            :integer,               :precision => 10, :scale => 0
  end

  create_table "EVENT_RECORD", :id => false, :force => true do |t|
    t.column "ID",             :integer,                :precision => 10, :scale => 0, :null => false
    t.column "EVENT_CODE",     :string,   :limit => 10,                                :null => false
    t.column "EVENT_NAME",     :string,   :limit => 64
    t.column "M_EVENT_TYPE",   :string,   :limit => 32
    t.column "PROJECT_CODE",   :string,   :limit => 20
    t.column "CURRENT_STATUS", :string,   :limit => 10
    t.column "EVENT_SPONSOR",  :string,   :limit => 10
    t.column "EVENT_TIME",     :datetime
  end

  add_index "EVENT_RECORD", ["EVENT_CODE"], :name => "AK_AK_TEMP_EVENT_RE", :unique => true

  create_table "FAVORITE", :id => false, :force => true do |t|
    t.column "OPERATOR",      :string,  :limit => 8,   :null => false
    t.column "NO",            :integer,                :null => false
    t.column "TIP_MSG",       :string,  :limit => 40
    t.column "FUNCTION_DECI", :string,  :limit => 40
    t.column "WINDOW_URL",    :string,  :limit => 100
    t.column "FOLDER_ID",     :integer
  end

  create_table "FAVORITE_FOLDER", :id => false, :force => true do |t|
    t.column "OPERATOR",    :string,  :limit => 8,  :null => false
    t.column "FOLDER_ID",   :integer,               :null => false
    t.column "FOLDER_NAME", :string,  :limit => 20, :null => false
    t.column "UP_FOLDER",   :integer
  end

  create_table "LOCAL_FUNCTION_CONTROL", :id => false, :force => true do |t|
    t.column "ID",             :string, :limit => 10
    t.column "FUNCTION_CLASS", :string, :limit => 10, :null => false
    t.column "FUNCTION_ITEM",  :string, :limit => 10, :null => false
    t.column "RIGHT_ONE",      :string, :limit => 8
    t.column "RIGHT_SECOND",   :string, :limit => 8
    t.column "RIGHT_THIRD",    :string, :limit => 8
    t.column "OPERATOR_ID",    :string, :limit => 8,  :null => false
  end

  create_table "OPERATOR", :id => false, :force => true do |t|
    t.column "OPER_ID",     :string,   :limit => 8,                                 :null => false
    t.column "DPT_NO",      :string,   :limit => 8
    t.column "NAME",        :string,   :limit => 8
    t.column "PSWD",        :string,   :limit => 16
    t.column "CREATE_DATE", :datetime
    t.column "CREATEBY",    :string,   :limit => 8
    t.column "TEL",         :string,   :limit => 16
    t.column "ADDRESS",     :string,   :limit => 64
    t.column "ID",          :integer,                :precision => 10, :scale => 0
  end

  create_table "OPERATOR_WORKS", :id => false, :force => true do |t|
    t.column "OPER_ID",           :string,   :limit => 8,                                :null => false
    t.column "PERSON_CLASS_CODE", :string,   :limit => 2,                                :null => false
    t.column "PROXY",             :string,   :limit => 1
    t.column "FLAG",              :string,   :limit => 4
    t.column "PROXY_OPER",        :string,   :limit => 8
    t.column "GRANT_ID",          :string,   :limit => 8
    t.column "GRANT_DATE",        :datetime
    t.column "ID",                :integer,               :precision => 10, :scale => 0
  end

  add_index "OPERATOR_WORKS", ["PERSON_CLASS_CODE"], :name => "REF_23_FK"
  add_index "OPERATOR_WORKS", ["OPER_ID"], :name => "REF_979474_FK"

# Could not dump table "PARAM" because of following ActiveRecord::StatementInvalid
#   Iconv::IllegalSequence: "\267\242生意外\241\243": EXEC sp_helpindex 'PARAM'

  create_table "PARM_CLASSIFY", :id => false, :force => true do |t|
    t.column "CLASS_CODE",      :string, :limit => 3,                   :null => false
    t.column "MODULE_CODE",     :string, :limit => 4,                   :null => false
    t.column "CLASS_NAME",      :string, :limit => 64
    t.column "SINGLE_VAL_FLAG", :string, :limit => 1,  :default => "N", :null => false
  end

  create_table "PARM_MAINTAIN_INI", :id => false, :force => true do |t|
    t.column "PARM_NO",    :integer,               :precision => 5, :scale => 0, :null => false
    t.column "LABEL",      :string,  :limit => 30
    t.column "IDENTIFIER", :string,  :limit => 30
    t.column "DW_NAME",    :string,  :limit => 30
    t.column "VISIBLE",    :string,  :limit => 1
    t.column "CLASS_CODE", :string,  :limit => 3
    t.column "WIDTH",      :integer,               :precision => 3, :scale => 0
    t.column "RIGHT_ITEM", :string,  :limit => 64
  end

  create_table "PARM_SINGLE", :id => false, :force => true do |t|
    t.column "COE_NO",     :integer,                :precision => 3,  :scale => 0, :null => false
    t.column "CLASS_CODE", :string,  :limit => 3
    t.column "COE_NAME",   :string,  :limit => 36
    t.column "IDENTIFIER", :string,  :limit => 30
    t.column "COE_VALUE",  :decimal,                :precision => 16, :scale => 6
    t.column "VALUE",      :string,  :limit => 32
    t.column "COE_NOTE",   :string,  :limit => 128
  end

  add_index "PARM_SINGLE", ["IDENTIFIER"], :name => "COEF_ID"

  create_table "PARM_VALUES", :id => false, :force => true do |t|
    t.column "PARM_NO", :integer,               :precision => 5, :scale => 0, :null => false
    t.column "VALUE",   :string,  :limit => 16,                               :null => false
    t.column "NAME",    :string,  :limit => 32
  end

  create_table "PERSON_CLASS", :id => false, :force => true do |t|
    t.column "PERSON_CLASS_CODE", :string,  :limit => 2,                                 :null => false
    t.column "PERSON_CLASS_NAME", :string,  :limit => 60
    t.column "FLAG",              :string,  :limit => 32
    t.column "ID",                :integer,               :precision => 10, :scale => 0
  end

  create_table "PRJ_CON_RELA", :id => false, :force => true do |t|
    t.column "ID",             :integer,               :precision => 10, :scale => 0, :null => false
    t.column "PROJECT_CODE",   :string,  :limit => 20
    t.column "PRODUCT_CODE",   :string,  :limit => 10
    t.column "PRODUCT_VERS",   :string,  :limit => 10
    t.column "CONFIGURE_CODE", :string,  :limit => 16
    t.column "CONFIGURE_VERS", :string,  :limit => 10
    t.column "CONF_M_RESPON",  :string,  :limit => 32
  end

  create_table "PRODUCT_COMP_CONF", :id => false, :force => true do |t|
    t.column "ID",             :integer,                 :precision => 10, :scale => 0, :null => false
    t.column "CONFIGURE_CODE", :string,  :limit => 16
    t.column "H_CONFIG_VERS",  :string,  :limit => 10
    t.column "PRODUCT_CODE",   :string,  :limit => 10
    t.column "PRODUCT_VERS",   :string,  :limit => 10
    t.column "ACTIVE_STATUS",  :string,  :limit => 50
    t.column "DEVELOP_PATH",   :string,  :limit => 1024
    t.column "AUTO_DOWN",      :string,  :limit => 1
    t.column "AUTO_UP",        :string,  :limit => 1
  end

  add_index "PRODUCT_COMP_CONF", ["PRODUCT_CODE", "PRODUCT_VERS", "CONFIGURE_CODE", "H_CONFIG_VERS"], :name => "AK_AK_PRODUCT_COMP_CO_PRODUCT_", :unique => true

  create_table "PROJECT_MSG", :id => false, :force => true do |t|
    t.column "ID",                  :integer,               :precision => 10, :scale => 0, :null => false
    t.column "PROJECT_CODE",        :string,  :limit => 20
    t.column "PROJECT_NAME",        :string,  :limit => 64
    t.column "PROJECT_STATE",       :string,  :limit => 32
    t.column "PROJECT_MANAGER",     :string,  :limit => 32
    t.column "PROJECT_CONF_PERSON", :string,  :limit => 32
    t.column "DUTY_PERSON",         :string,  :limit => 32
  end

  add_index "PROJECT_MSG", ["PROJECT_CODE"], :name => "AK_AK_PRJ_PROJECT_", :unique => true

  create_table "PUB_ERROR_SHOW", :id => false, :force => true do |t|
    t.column "ERROR_NO",      :integer,                :precision => 12, :scale => 0, :null => false
    t.column "OBJECT_NAME",   :string,   :limit => 32
    t.column "OBJECT_TYPE",   :string,   :limit => 20
    t.column "ERROR_CODE",    :integer,                :precision => 8,  :scale => 0
    t.column "ERROR_ROW",     :integer,                :precision => 6,  :scale => 0
    t.column "ERROR_TEXT",    :string
    t.column "MACHINE_NAME",  :string,   :limit => 20
    t.column "MACHINE_USER",  :string,   :limit => 20
    t.column "DATABASE_USER", :string,   :limit => 30
    t.column "ERROR_TIME",    :datetime
    t.column "SESSION_ID",    :string,   :limit => 12
    t.column "REMARK",        :string
    t.column "CURRENT_FLAG",  :integer,                :precision => 1,  :scale => 0
  end

  add_index "PUB_ERROR_SHOW", ["MACHINE_NAME"], :name => "PUB_ERROR_SHOW_INDEX"

  create_table "RELA_CHG_CONFIGURE", :id => false, :force => true do |t|
    t.column "ID",             :integer,               :precision => 10, :scale => 0, :null => false
    t.column "EVENT_CODE",     :string,  :limit => 10
    t.column "CONFIGURE_CODE", :string,  :limit => 16
    t.column "CONFIGURE_VERS", :string,  :limit => 10
    t.column "M_CONFIG_FLAG",  :string,  :limit => 32
  end

  add_index "RELA_CHG_CONFIGURE", ["EVENT_CODE", "CONFIGURE_CODE"], :name => "AK_AK_RELA_CHG_RELA_CHG", :unique => true

  create_table "RESCURE_METHOD", :id => false, :force => true do |t|
    t.column "ID",          :integer,                 :precision => 10, :scale => 0, :null => false
    t.column "METHOD_CODE", :string,   :limit => 10
    t.column "DOCUMENT_SN", :string,   :limit => 20
    t.column "METHOD_NAME", :string,   :limit => 128
    t.column "PLAN_DATE",   :datetime
    t.column "REAL_DATE",   :datetime
  end

  add_index "RESCURE_METHOD", ["METHOD_CODE"], :name => "AK_AK_METHOD_RESCURE_", :unique => true

  create_table "RT_FILTER", :id => false, :force => true do |t|
    t.column "DATASOURCE", :string,  :limit => 60,                                :null => false
    t.column "FILTER_COL", :string,  :limit => 64
    t.column "FILTER_SQL", :string
    t.column "COL_OR_SQL", :string,  :limit => 1
    t.column "IS_FILTER",  :string,  :limit => 1
    t.column "IS_DEPT",    :string,  :limit => 1
    t.column "ORDER_COL",  :integer,               :precision => 5,  :scale => 0
    t.column "REMARKS",    :string
    t.column "ID",         :integer,               :precision => 10, :scale => 0
  end

  create_table "RT_FUNCTION_GROUP", :id => false, :force => true do |t|
    t.column "FUNC_GROUP_ID",   :integer,               :precision => 10, :scale => 0, :null => false
    t.column "FUNC_GROUP_NAME", :string,  :limit => 60
    t.column "UP_GROUP_ID",     :integer,               :precision => 10, :scale => 0
    t.column "ORDER_COL",       :string,  :limit => 8
    t.column "DEL_FLAG",        :string,  :limit => 1
    t.column "ID",              :integer,               :precision => 10, :scale => 0
  end

  create_table "RT_MODIFY_LOG", :id => false, :force => true do |t|
    t.column "SEQ_NO",         :integer,                 :precision => 9,  :scale => 0, :null => false
    t.column "APP_DATE",       :datetime
    t.column "APP_MAN",        :string,   :limit => 30
    t.column "MODIFY_CONTENT", :string,   :limit => 250
    t.column "MODIFY_REASON",  :string,   :limit => 250
    t.column "ASSIGN_MAN",     :string,   :limit => 8
    t.column "MODIFY_MAN",     :string,   :limit => 8
    t.column "MODIFY_DATE",    :datetime
    t.column "MODIFY_THING",   :string,   :limit => 250
    t.column "ID",             :integer,                 :precision => 10, :scale => 0
  end

  create_table "RT_POSITION_RIGHT_ITEM", :id => false, :force => true do |t|
    t.column "ROW_ID",            :integer,              :precision => 10, :scale => 0, :null => false
    t.column "FUNC_ID",           :integer,              :precision => 10, :scale => 0
    t.column "PERSON_CLASS_CODE", :string,  :limit => 2
    t.column "RIGHT_ITEM_ID",     :integer,              :precision => 10, :scale => 0
    t.column "FLAG",              :string,  :limit => 1
    t.column "GRANT_TYPE",        :string,  :limit => 1
    t.column "ID",                :integer,              :precision => 10, :scale => 0
  end

  add_index "RT_POSITION_RIGHT_ITEM", ["PERSON_CLASS_CODE", "FUNC_ID", "RIGHT_ITEM_ID"], :name => "AK_AK_POSITION_RIGHT__RT_POSIT", :unique => true
  add_index "RT_POSITION_RIGHT_ITEM", ["FUNC_ID"], :name => "IDX_RT_POS_RT_ITEM_FUNC"
  add_index "RT_POSITION_RIGHT_ITEM", ["PERSON_CLASS_CODE"], :name => "IDX_RT_POS_RT_ITEM_POS"

  create_table "RT_RIGHT_ITEM", :id => false, :force => true do |t|
    t.column "RIGHT_ITEM_ID",   :integer,               :precision => 10, :scale => 0, :null => false
    t.column "FUNC_ID",         :integer,               :precision => 10, :scale => 0, :null => false
    t.column "RIGHT_ITEM_NAME", :string,  :limit => 64
    t.column "RIGHT_ITEM_DES",  :string,  :limit => 64
    t.column "COMMANDTARGET",   :string,  :limit => 30
    t.column "ORDER_COL",       :string,  :limit => 8
    t.column "ID",              :integer,               :precision => 10, :scale => 0
  end

  create_table "RT_SYSTEM_FUNCTION", :id => false, :force => true do |t|
    t.column "FUNC_ID",       :integer,                :precision => 10, :scale => 0, :null => false
    t.column "FUNC_GROUP_ID", :integer,                :precision => 10, :scale => 0
    t.column "FUNC_NAME",     :string,  :limit => 40
    t.column "DATASOURCE",    :string,  :limit => 60
    t.column "TARGET",        :string,  :limit => 100
    t.column "ISHAVECHILD",   :string,  :limit => 1
    t.column "ORDER_COL",     :string,  :limit => 8
    t.column "FILTER_COL",    :string,  :limit => 64
    t.column "IS_FILTER",     :string,  :limit => 1
    t.column "IS_DEPT",       :string,  :limit => 1
    t.column "DEL_FLAG",      :string,  :limit => 1
    t.column "FUNC_PARAM",    :string,  :limit => 128
    t.column "ID",            :integer,                :precision => 10, :scale => 0
  end

# Could not dump table "SEQUENCE_ASSETS_NO" because of following ActiveRecord::StatementInvalid
#   Iconv::IllegalSequence: "\267\242生意外\241\243": EXEC sp_helpindex 'SEQUENCE_ASSETS_NO'

  create_table "SOFTWARE_PRODUCT", :id => false, :force => true do |t|
    t.column "ID",           :integer,               :precision => 10, :scale => 0, :null => false
    t.column "PRODUCT_CODE", :string,  :limit => 10
    t.column "H_PRO_VERS",   :string,  :limit => 10
    t.column "PRODUCT_NAME", :string,  :limit => 64
  end

  add_index "SOFTWARE_PRODUCT", ["PRODUCT_CODE"], :name => "AK_PRODUCT_SOFTWARE", :unique => true

  create_table "SOFTWARE_PRODUCT_VER", :id => false, :force => true do |t|
    t.column "ID",                  :integer,               :precision => 10, :scale => 0, :null => false
    t.column "PRODUCT_CODE",        :string,  :limit => 10
    t.column "PRODUCT_VERS",        :string,  :limit => 10
    t.column "COMMENT",             :string,  :limit => 30
    t.column "PRODUCT_CONF_PERSON", :string,  :limit => 32
  end

  add_index "SOFTWARE_PRODUCT_VER", ["PRODUCT_CODE", "PRODUCT_VERS"], :name => "AK_SOFTWARE", :unique => true

  create_table "SYS_ACCEPTER", :id => false, :force => true do |t|
    t.column "MESSAGE_ID", :integer,              :precision => 18, :scale => 0, :null => false
    t.column "TO_USER",    :string,  :limit => 8,                                :null => false
    t.column "FLAG",       :string,  :limit => 1,                                :null => false
  end

  add_index "SYS_ACCEPTER", ["MESSAGE_ID"], :name => "IF625_SYS_ACCEPTER"

  create_table "SYS_CLASS_DATAWINDOW", :id => false, :force => true do |t|
    t.column "DW_NAME",  :string, :limit => 64,  :null => false
    t.column "PBD_NAME", :string, :limit => 64
    t.column "REMARKS",  :string, :limit => 128
  end

  create_table "SYS_MESSAGE", :id => false, :force => true do |t|
    t.column "MESSAGE_ID", :integer,                :precision => 18, :scale => 0, :null => false
    t.column "FROM_USER",  :string,   :limit => 8
    t.column "SEND_TIME",  :datetime
    t.column "HIERACHY",   :string,   :limit => 1
    t.column "TITLE",      :string,   :limit => 40
    t.column "CONTENT",    :text
    t.column "STATUS",     :string,   :limit => 1
  end

  create_table "SYS_SPECIAL_ROLE", :id => false, :force => true do |t|
    t.column "FLAG",              :string, :limit => 16, :null => false
    t.column "PERSON_CLASS_CODE", :string, :limit => 2,  :null => false
    t.column "REMARK",            :string
  end

  create_table "pbcatcol", :id => false, :force => true do |t|
    t.column "pbc_tnam", :string,  :limit => 30
    t.column "pbc_tid",  :integer
    t.column "pbc_ownr", :string,  :limit => 30
    t.column "pbc_cnam", :string,  :limit => 30
    t.column "pbc_cid",  :integer
    t.column "pbc_labl", :string,  :limit => 254
    t.column "pbc_lpos", :integer
    t.column "pbc_hdr",  :string,  :limit => 254
    t.column "pbc_hpos", :integer
    t.column "pbc_jtfy", :integer
    t.column "pbc_mask", :string,  :limit => 31
    t.column "pbc_case", :integer
    t.column "pbc_hght", :integer
    t.column "pbc_wdth", :integer
    t.column "pbc_ptrn", :string,  :limit => 31
    t.column "pbc_bmap", :string,  :limit => 1
    t.column "pbc_init", :string,  :limit => 254
    t.column "pbc_cmnt", :string,  :limit => 254
    t.column "pbc_edit", :string,  :limit => 31
    t.column "pbc_tag",  :string,  :limit => 254
    t.column "pbc_tnam", :string,  :limit => 30
    t.column "pbc_tid",  :integer
    t.column "pbc_ownr", :string,  :limit => 30
    t.column "pbc_cnam", :string,  :limit => 30
    t.column "pbc_cid",  :integer
    t.column "pbc_labl", :string,  :limit => 254
    t.column "pbc_lpos", :integer
    t.column "pbc_hdr",  :string,  :limit => 254
    t.column "pbc_hpos", :integer
    t.column "pbc_jtfy", :integer
    t.column "pbc_mask", :string,  :limit => 31
    t.column "pbc_case", :integer
    t.column "pbc_hght", :integer
    t.column "pbc_wdth", :integer
    t.column "pbc_ptrn", :string,  :limit => 31
    t.column "pbc_bmap", :string,  :limit => 1
    t.column "pbc_init", :string,  :limit => 254
    t.column "pbc_cmnt", :string,  :limit => 254
    t.column "pbc_edit", :string,  :limit => 31
    t.column "pbc_tag",  :string,  :limit => 254
  end

  add_index "pbcatcol", ["pbc_tnam", "pbc_ownr", "pbc_cnam"], :name => "pbcatcol_idx", :unique => true

  create_table "pbcatcol", :id => false, :force => true do |t|
    t.column "pbc_tnam", :string,  :limit => 30
    t.column "pbc_tid",  :integer
    t.column "pbc_ownr", :string,  :limit => 30
    t.column "pbc_cnam", :string,  :limit => 30
    t.column "pbc_cid",  :integer
    t.column "pbc_labl", :string,  :limit => 254
    t.column "pbc_lpos", :integer
    t.column "pbc_hdr",  :string,  :limit => 254
    t.column "pbc_hpos", :integer
    t.column "pbc_jtfy", :integer
    t.column "pbc_mask", :string,  :limit => 31
    t.column "pbc_case", :integer
    t.column "pbc_hght", :integer
    t.column "pbc_wdth", :integer
    t.column "pbc_ptrn", :string,  :limit => 31
    t.column "pbc_bmap", :string,  :limit => 1
    t.column "pbc_init", :string,  :limit => 254
    t.column "pbc_cmnt", :string,  :limit => 254
    t.column "pbc_edit", :string,  :limit => 31
    t.column "pbc_tag",  :string,  :limit => 254
    t.column "pbc_tnam", :string,  :limit => 30
    t.column "pbc_tid",  :integer
    t.column "pbc_ownr", :string,  :limit => 30
    t.column "pbc_cnam", :string,  :limit => 30
    t.column "pbc_cid",  :integer
    t.column "pbc_labl", :string,  :limit => 254
    t.column "pbc_lpos", :integer
    t.column "pbc_hdr",  :string,  :limit => 254
    t.column "pbc_hpos", :integer
    t.column "pbc_jtfy", :integer
    t.column "pbc_mask", :string,  :limit => 31
    t.column "pbc_case", :integer
    t.column "pbc_hght", :integer
    t.column "pbc_wdth", :integer
    t.column "pbc_ptrn", :string,  :limit => 31
    t.column "pbc_bmap", :string,  :limit => 1
    t.column "pbc_init", :string,  :limit => 254
    t.column "pbc_cmnt", :string,  :limit => 254
    t.column "pbc_edit", :string,  :limit => 31
    t.column "pbc_tag",  :string,  :limit => 254
  end

  add_index "pbcatcol", ["pbc_tnam", "pbc_ownr", "pbc_cnam"], :name => "pbcatcol_idx", :unique => true

  create_table "pbcatedt", :id => false, :force => true do |t|
    t.column "pbe_name", :string,  :limit => 30,  :null => false
    t.column "pbe_edit", :string,  :limit => 254
    t.column "pbe_type", :integer,                :null => false
    t.column "pbe_cntr", :integer
    t.column "pbe_seqn", :integer,                :null => false
    t.column "pbe_flag", :integer
    t.column "pbe_work", :string,  :limit => 32
    t.column "pbe_name", :string,  :limit => 30,  :null => false
    t.column "pbe_edit", :string,  :limit => 254
    t.column "pbe_type", :integer,                :null => false
    t.column "pbe_cntr", :integer
    t.column "pbe_seqn", :integer,                :null => false
    t.column "pbe_flag", :integer
    t.column "pbe_work", :string,  :limit => 32
  end

  add_index "pbcatedt", ["pbe_name", "pbe_seqn"], :name => "pbcatedt_idx", :unique => true

  create_table "pbcatedt", :id => false, :force => true do |t|
    t.column "pbe_name", :string,  :limit => 30,  :null => false
    t.column "pbe_edit", :string,  :limit => 254
    t.column "pbe_type", :integer,                :null => false
    t.column "pbe_cntr", :integer
    t.column "pbe_seqn", :integer,                :null => false
    t.column "pbe_flag", :integer
    t.column "pbe_work", :string,  :limit => 32
    t.column "pbe_name", :string,  :limit => 30,  :null => false
    t.column "pbe_edit", :string,  :limit => 254
    t.column "pbe_type", :integer,                :null => false
    t.column "pbe_cntr", :integer
    t.column "pbe_seqn", :integer,                :null => false
    t.column "pbe_flag", :integer
    t.column "pbe_work", :string,  :limit => 32
  end

  add_index "pbcatedt", ["pbe_name", "pbe_seqn"], :name => "pbcatedt_idx", :unique => true

  create_table "pbcatfmt", :id => false, :force => true do |t|
    t.column "pbf_name", :string,  :limit => 30,  :null => false
    t.column "pbf_frmt", :string,  :limit => 254, :null => false
    t.column "pbf_type", :integer,                :null => false
    t.column "pbf_cntr", :integer
    t.column "pbf_name", :string,  :limit => 30,  :null => false
    t.column "pbf_frmt", :string,  :limit => 254, :null => false
    t.column "pbf_type", :integer,                :null => false
    t.column "pbf_cntr", :integer
  end

  add_index "pbcatfmt", ["pbf_name"], :name => "pbcatfmt_idx", :unique => true

  create_table "pbcatfmt", :id => false, :force => true do |t|
    t.column "pbf_name", :string,  :limit => 30,  :null => false
    t.column "pbf_frmt", :string,  :limit => 254, :null => false
    t.column "pbf_type", :integer,                :null => false
    t.column "pbf_cntr", :integer
    t.column "pbf_name", :string,  :limit => 30,  :null => false
    t.column "pbf_frmt", :string,  :limit => 254, :null => false
    t.column "pbf_type", :integer,                :null => false
    t.column "pbf_cntr", :integer
  end

  add_index "pbcatfmt", ["pbf_name"], :name => "pbcatfmt_idx", :unique => true

  create_table "pbcattbl", :id => false, :force => true do |t|
    t.column "pbt_tnam", :string,  :limit => 30
    t.column "pbt_tid",  :integer
    t.column "pbt_ownr", :string,  :limit => 30
    t.column "pbd_fhgt", :integer
    t.column "pbd_fwgt", :integer
    t.column "pbd_fitl", :string,  :limit => 1
    t.column "pbd_funl", :string,  :limit => 1
    t.column "pbd_fchr", :integer
    t.column "pbd_fptc", :integer
    t.column "pbd_ffce", :string,  :limit => 32
    t.column "pbh_fhgt", :integer
    t.column "pbh_fwgt", :integer
    t.column "pbh_fitl", :string,  :limit => 1
    t.column "pbh_funl", :string,  :limit => 1
    t.column "pbh_fchr", :integer
    t.column "pbh_fptc", :integer
    t.column "pbh_ffce", :string,  :limit => 32
    t.column "pbl_fhgt", :integer
    t.column "pbl_fwgt", :integer
    t.column "pbl_fitl", :string,  :limit => 1
    t.column "pbl_funl", :string,  :limit => 1
    t.column "pbl_fchr", :integer
    t.column "pbl_fptc", :integer
    t.column "pbl_ffce", :string,  :limit => 32
    t.column "pbt_cmnt", :string,  :limit => 254
    t.column "pbt_tnam", :string,  :limit => 30
    t.column "pbt_tid",  :integer
    t.column "pbt_ownr", :string,  :limit => 30
    t.column "pbd_fhgt", :integer
    t.column "pbd_fwgt", :integer
    t.column "pbd_fitl", :string,  :limit => 1
    t.column "pbd_funl", :string,  :limit => 1
    t.column "pbd_fchr", :integer
    t.column "pbd_fptc", :integer
    t.column "pbd_ffce", :string,  :limit => 32
    t.column "pbh_fhgt", :integer
    t.column "pbh_fwgt", :integer
    t.column "pbh_fitl", :string,  :limit => 1
    t.column "pbh_funl", :string,  :limit => 1
    t.column "pbh_fchr", :integer
    t.column "pbh_fptc", :integer
    t.column "pbh_ffce", :string,  :limit => 32
    t.column "pbl_fhgt", :integer
    t.column "pbl_fwgt", :integer
    t.column "pbl_fitl", :string,  :limit => 1
    t.column "pbl_funl", :string,  :limit => 1
    t.column "pbl_fchr", :integer
    t.column "pbl_fptc", :integer
    t.column "pbl_ffce", :string,  :limit => 32
    t.column "pbt_cmnt", :string,  :limit => 254
  end

  add_index "pbcattbl", ["pbt_tnam", "pbt_ownr"], :name => "pbcattbl_idx", :unique => true

  create_table "pbcattbl", :id => false, :force => true do |t|
    t.column "pbt_tnam", :string,  :limit => 30
    t.column "pbt_tid",  :integer
    t.column "pbt_ownr", :string,  :limit => 30
    t.column "pbd_fhgt", :integer
    t.column "pbd_fwgt", :integer
    t.column "pbd_fitl", :string,  :limit => 1
    t.column "pbd_funl", :string,  :limit => 1
    t.column "pbd_fchr", :integer
    t.column "pbd_fptc", :integer
    t.column "pbd_ffce", :string,  :limit => 32
    t.column "pbh_fhgt", :integer
    t.column "pbh_fwgt", :integer
    t.column "pbh_fitl", :string,  :limit => 1
    t.column "pbh_funl", :string,  :limit => 1
    t.column "pbh_fchr", :integer
    t.column "pbh_fptc", :integer
    t.column "pbh_ffce", :string,  :limit => 32
    t.column "pbl_fhgt", :integer
    t.column "pbl_fwgt", :integer
    t.column "pbl_fitl", :string,  :limit => 1
    t.column "pbl_funl", :string,  :limit => 1
    t.column "pbl_fchr", :integer
    t.column "pbl_fptc", :integer
    t.column "pbl_ffce", :string,  :limit => 32
    t.column "pbt_cmnt", :string,  :limit => 254
    t.column "pbt_tnam", :string,  :limit => 30
    t.column "pbt_tid",  :integer
    t.column "pbt_ownr", :string,  :limit => 30
    t.column "pbd_fhgt", :integer
    t.column "pbd_fwgt", :integer
    t.column "pbd_fitl", :string,  :limit => 1
    t.column "pbd_funl", :string,  :limit => 1
    t.column "pbd_fchr", :integer
    t.column "pbd_fptc", :integer
    t.column "pbd_ffce", :string,  :limit => 32
    t.column "pbh_fhgt", :integer
    t.column "pbh_fwgt", :integer
    t.column "pbh_fitl", :string,  :limit => 1
    t.column "pbh_funl", :string,  :limit => 1
    t.column "pbh_fchr", :integer
    t.column "pbh_fptc", :integer
    t.column "pbh_ffce", :string,  :limit => 32
    t.column "pbl_fhgt", :integer
    t.column "pbl_fwgt", :integer
    t.column "pbl_fitl", :string,  :limit => 1
    t.column "pbl_funl", :string,  :limit => 1
    t.column "pbl_fchr", :integer
    t.column "pbl_fptc", :integer
    t.column "pbl_ffce", :string,  :limit => 32
    t.column "pbt_cmnt", :string,  :limit => 254
  end

  add_index "pbcattbl", ["pbt_tnam", "pbt_ownr"], :name => "pbcattbl_idx", :unique => true

  create_table "pbcatvld", :id => false, :force => true do |t|
    t.column "pbv_name", :string,  :limit => 30,  :null => false
    t.column "pbv_vald", :string,  :limit => 254, :null => false
    t.column "pbv_type", :integer,                :null => false
    t.column "pbv_cntr", :integer
    t.column "pbv_msg",  :string,  :limit => 254
    t.column "pbv_name", :string,  :limit => 30,  :null => false
    t.column "pbv_vald", :string,  :limit => 254, :null => false
    t.column "pbv_type", :integer,                :null => false
    t.column "pbv_cntr", :integer
    t.column "pbv_msg",  :string,  :limit => 254
  end

  add_index "pbcatvld", ["pbv_name"], :name => "pbcatvld_idx", :unique => true

  create_table "pbcatvld", :id => false, :force => true do |t|
    t.column "pbv_name", :string,  :limit => 30,  :null => false
    t.column "pbv_vald", :string,  :limit => 254, :null => false
    t.column "pbv_type", :integer,                :null => false
    t.column "pbv_cntr", :integer
    t.column "pbv_msg",  :string,  :limit => 254
    t.column "pbv_name", :string,  :limit => 30,  :null => false
    t.column "pbv_vald", :string,  :limit => 254, :null => false
    t.column "pbv_type", :integer,                :null => false
    t.column "pbv_cntr", :integer
    t.column "pbv_msg",  :string,  :limit => 254
  end

  add_index "pbcatvld", ["pbv_name"], :name => "pbcatvld_idx", :unique => true

end
